logging:
    level:
        com.home: DEBUG
spring:
    application:
        name: standard_home
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://121.43.186.43:3306/cxf_excel?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF8
        username: cxfhrcf
        password: '11300519'
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
server:
    port: 8989

swagger:
    basepackage: com.home.rest
    service:
        name: cxf_excel
        description: 一张虎
        developer: chenxf

jwt:
  secret: CX*g@hjty
  expiration: 7200
  header: access-token
  tokenHead: token-header

mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    not-empty: false
    identity: MYSQL


auth:
    jwt:
        secret: Xe*g@1jda
        expiration: 7200
        header: access-token